export const CATEGORIES = [
  'animal',
  'auto',
  'auto equipment',
  'bike',
  'book',
  'CD - Music',
  'computer',
  'computer hardware',
  'console',
  'decoration',
  'Do-It-Yourself',
  'DVD - Movie',
  'electrical appliances',
  'furniture',
  'game',
  'gardening',
  'gastronomy',
  'item of clothing',
  'moto',
  'moto equipment',
  'music intrument',
  'phone',
  'piece of jewelry',
  'scooter',
  'shoe',
  'sport',
  'ticket',
  'toy',
  'truck',
  'truck equipment',
  'vehicle',
  'vehicle equipment',
  'video game',
] as const

export const MAX_IMAGE_SIZE = 1048576
