export const CATEGORIES = [
  'vehicle',
  'vehicle equipment',
  'auto',
  'auto equipment',
  'moto',
  'moto equipment',
  'truck',
  'truck equipment',
  'item of clothing',
  'shoe',
  'piece of jewelry',
  'furniture',
  'electrical appliances',
  'decoration',
  'Do-It-Yourself',
  'gardening',
  'computer',
  'computer hardware',
  'console',
  'video game',
  'phone',
  'DVD - Movie',
  'CD - Music',
  'book',
  'bike',
  'scooter',
  'sport',
  'music intrument',
  'game',
  'toy',
  'gastronomy',
  'animal',
  'ticket',
] as const

export const MAX_IMAGE_SIZE = 1048576
