const categories = [
  'furniture' as const,
  'household appliance' as const,
  'electronic device' as const,
  'plant' as const,
  'pet' as const,
  'cat' as const,
  'dog' as const,
  'bird' as const,
  'horse' as const,
  'turtle' as const,
  'computer' as const,
  'smartphone' as const,
  'laptop' as const,
  'vehicle' as const,
  'bicycle' as const,
  'clothes' as const,
  'screen' as const,
  'printer' as const,
  'dishes' as const,
  'keyboard' as const,
  'headset' as const,
]

export default categories
