const categories = [
  'vehicle' as const,
  'vehicle equipment' as const,
  'auto' as const,
  'auto equipment' as const,
  'moto' as const,
  'moto equipment' as const,
  'truck' as const,
  'truck equipment' as const,
  'item of clothing' as const,
  'shoe' as const,
  'piece of jewelry' as const,
  'furniture' as const,
  'electrical appliances' as const,
  'decoration' as const,
  'Do-It-Yourself' as const,
  'gardening' as const,
  'computer' as const,
  'computer hardware' as const,
  'console' as const,
  'video game' as const,
  'phone' as const,
  'DVD - Movie' as const,
  'CD - Music' as const,
  'book' as const,
  'bike' as const,
  'scooter' as const,
  'sport' as const,
  'music intrument' as const,
  'game' as const,
  'toy' as const,
  'gastronomy' as const,
  'animal' as const,
  'ticket' as const,
]

export default categories
